In [21]:
import pandas as pd

In [22]:
rawdf =  pd.read_csv('raw_data.csv')
col = ['UserID','Raw','Positive=1']
rawdf = rawdf.reindex(labels=col,axis=1)

In [23]:
rawdf.head()

,UserID,Raw,Positive=1
0,76561197969686815,As of writing 1442.5 iLvl Scrapper with too ma...,0
1,76561199242882877,If you like the grind its good and its battle ...,1
2,76561199145677441,üëç,1
3,76561197988379887,grindy ass game without much meat on the bone,0
4,76561198080925232,If you love your time eaten away and wasted by...,0

In [24]:
rawdf = rawdf.astype({'UserID':'str'})

In [25]:
reviewdf = pd.read_pickle('stemming_data(ÏÉàÏãúÏûë).pkl')
l = list(reviewdf['Lemmatized'])
l2 = list(reviewdf['Review'])
l3 = []
for i in range(len(reviewdf)):
    x = l[i]
    y = ' '
    for word in x:
        y += word
        y += ' '
    l3.append(y)     
   
reviewdf['line'] = l3

col = ['line','Review','UserID']
reviewdf = reviewdf.reindex(labels=col,axis=1)
reviewdf.head()

,line,Review,UserID
0,write ilvl scrapper fun fault akin soft poe e...,as of writing ilvl scrapper with too m...,76561197969686815
1,grind battle design,if you like the grind its good and its battle...,76561199242882877
3,grind meat bone,grindy ass game without much meat on the bone,76561197988379887
4,love time eat away waste bogus chance mechani...,if you love your time eaten away and wasted b...,76561198080925232
6,mmo rouge rpg aint exclude bot prob kek fun s...,the games ok tho there r better mmos and rou...,76561199072662970

In [26]:
type(reviewdf['UserID'][0])

numpy.int64

In [27]:
reviewdf = reviewdf.astype({'UserID':'str'})

In [28]:
reviewdf = pd.merge(reviewdf, rawdf, how='inner', on='UserID')

In [29]:
proportiondf = pd.read_csv('./STM/result/topic_proportion.csv')
proportiondf  = proportiondf.drop(['Unnamed: 0', 'docnum','Day' , 'Recommend'], axis =1)

In [30]:
merge = pd.merge(reviewdf, proportiondf, how='inner', on='line')

merge = merge.drop(['line'], axis =1)

for i in range(1,17):
    merge[f'Topic{i}'] = merge[f'Topic{i}'].map(lambda x:('%.3f')%x)

In [31]:
names = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [32]:
for i in range(1,17):
    merge[names[i-1]] = list(merge[f'Topic{i}'])
    merge = merge.drop([f'Topic{i}'], axis =1)

In [33]:
merge=merge.drop(['UserID'], axis =1)
merge.head()

,Review,Raw,Positive=1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,as of writing ilvl scrapper with too m...,As of writing 1442.5 iLvl Scrapper with too ma...,0,0.010,0.007,0.008,0.079,0.014,0.005,0.015,0.033,0.057,0.095,0.009,0.085,0.030,0.036,0.204,0.314
1,if you love your time eaten away and wasted b...,If you love your time eaten away and wasted by...,0,0.020,0.024,0.012,0.053,0.021,0.180,0.025,0.021,0.170,0.019,0.032,0.053,0.019,0.273,0.054,0.022
2,the games ok tho there r better mmos and rou...,"the games ok tho, there r better mmos and roug...",0,0.036,0.028,0.028,0.062,0.039,0.041,0.087,0.139,0.052,0.036,0.095,0.122,0.044,0.116,0.057,0.017
3,huge absolutely massive time sink with littl...,"Huge, absolutely massive time sink with little...",0,0.026,0.020,0.008,0.091,0.087,0.020,0.056,0.024,0.042,0.025,0.109,0.125,0.042,0.123,0.174,0.027
4,feels a bit empty i love mmos and can often ...,Feels a bit empty. I love MMOS and can often c...,0,0.016,0.041,0.005,0.056,0.063,0.030,0.168,0.049,0.029,0.086,0.149,0.037,0.075,0.103,0.073,0.019

In [34]:
merge.to_csv('ÌÜ†ÌîΩ-Î¶¨Î∑∞Ìï©ÏÑ±.csv', index = False)