In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날역인(채운거)(최종).csv')

In [12]:
x = df.describe()

In [13]:
x.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/데이터분석.csv', encoding = 'utf-8-sig', index_label = True, index = True)

In [14]:
x

,date,subway,전날누적확진자,d+1,d+2,d+3,d+4,d+5,d+6,d+7,...,마스크,4인집합,평균기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),일적설량(cm),역갯수,인구
count,1.897500e+04,18975.00000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,...,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.000000,18975.00000,18975.000000
mean,2.019703e+07,168490.31610,121.672622,1.312885,1.307615,1.301186,1.294967,1.289170,1.282372,1.276838,...,0.142292,0.088274,12.980105,3.383926,2.202503,60.345191,6.519499,0.050198,9.36000,445271.276667
std,6.116574e+03,122308.98233,259.648379,3.438105,3.434624,3.429789,3.426578,3.423149,3.419211,3.416788,...,0.349359,0.283701,10.149696,11.657106,0.696618,15.655556,4.017261,0.411117,5.09036,141900.592347
min,2.019020e+07,7965.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-14.900000,0.000000,0.600000,17.900000,0.000000,0.000000,1.00000,164790.405600
25%,2.019081e+07,79735.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.600000,0.000000,1.700000,48.100000,3.000000,0.000000,5.00000,359293.069650
50%,2.020022e+07,140876.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,13.100000,0.000000,2.000000,60.500000,7.600000,0.000000,9.00000,418068.747400
75%,2.020082e+07,218324.50000,91.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,22.600000,0.300000,2.500000,71.500000,9.700000,0.000000,11.00000,513493.161650
max,2.021023e+07,765186.00000,1649.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,...,1.000000,1.000000,31.600000,103.100000,6.000000,96.300000,13.600000,5.000000,23.00000,963357.058600