In [1]:
import pandas as pd
import datetime

In [2]:
날씨df = pd.read_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/날씨/날씨.csv')
날씨df['date'] = 날씨df['date'].str.replace('-', '')
date = []
for j in 날씨df['date']:
    date.append(j)
date = set(date)
date = list(date)
date.sort()

In [3]:
역별자치구df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/주소/지하철역 주소.csv',  sep='\t')
for i in range(len(역별자치구df["주소"])):
    index = 역별자치구df["주소"][i].find('구 ')
    역별자치구df["주소"][i] = 역별자치구df["주소"][i][6:(index+1)]
역별자치구df = 역별자치구df.drop_duplicates('역명')
역별자치구df.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/주소/지하철역 주소(중복제거).csv', encoding = 'utf-8-sig', index_label = False, index = False)
역 = []
구 = []
for i in 역별자치구df['역명']:
    역.append(i)
for i in 역별자치구df['주소']:
    구.append(i)
역 = set(역)
역 = list(역)
역.sort()

구 = set(구)
구 = list(구)
구.sort()
역별자치구df

          역명    주소
0       가락시장   송파구
1    가산디지털단지   금천구
2         강남   강남구
3       강남구청   강남구
4         강동   강동구
..       ...   ...
267       홍제  서대문구
268       화곡   강서구
269      화랑대   노원구
270       회현    중구
271    효창공원앞   용산구

[234 rows x 2 columns]

In [4]:
지하철df1 =  pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/1/sub.csv')
지하철df2 =  pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/2/sub.csv')
지하철df1 = 지하철df1.drop(['하차총승객수','등록일자'],axis=1)
지하철df2 = 지하철df2.drop(['수정용','하차총승객수','등록일자'],axis=1)
지하철df1.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/1.csv', encoding = 'utf-8-sig', index_label = False, index = False)
지하철df2.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/2.csv', encoding = 'utf-8-sig', index_label = False, index = False)

C:\Users\LEE\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (0,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
지하철df =  pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/sub.csv')
for i in range(len(지하철df['역명'])):
    index = 지하철df["역명"][i].find('(')
    if not index == -1:
        지하철df['역명'][i] = 지하철df['역명'][i][:index]
지하철df = 지하철df[지하철df['역명'].isin(역)]
지하철df = pd.merge(지하철df, 역별자치구df, on ='역명', how='outer')
지하철df.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/지하철인코딩후/지하철역별.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [6]:
for i in 구:
    df = 지하철df
    X = df['주소'] == i
    Y = df[X]
    Y.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/자치구별/{i}.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [7]:
for i in 구:
    df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/자치구별/{i}.csv')
    date2 = []
    subway = []
    
    for k in date:
        df2 = df.loc[df['사용일자'] == int(k), '승차총승객수']
        a = df2.sum()
        date2.append(k)
        subway.append(a)

    df3 = pd.DataFrame(list(zip(date2,subway)), columns =['사용일자', '승차총승객수'])    
    df3['주소'] = i
    df3.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/자치구별/날짜합/{i}종합.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [8]:
코로나df = pd.read_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/코로나/서울시 코로나19 확진자 현황.csv')
코로나df = 코로나df.drop(['환자번호','국적','환자정보','여행력','접촉력','연번','조치사항','상태','이동경로','등록일', '수정일', '노출여부'],axis=1)
코로나df = 코로나df[코로나df['지역'].isin(구)]
코로나df.rename(columns = {'확진일' : 'date'}, inplace = True)
코로나df['date'] = 코로나df['date'].str.replace('-', '')
코로나df

           date    지역
1      20210228  영등포구
2      20210228  영등포구
3      20210228   동작구
4      20210228   송파구
5      20210228   성북구
...         ...   ...
28323  20200131   성북구
28324  20200130   마포구
28325  20200130   종로구
28326  20200130   중랑구
28327  20200124   강서구

[25005 rows x 2 columns]

In [9]:
for i in 구:
    df = 코로나df
    X = df['지역'] == i
    Y = df[X]
    Y.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/코로나/자치구별/{i}.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [12]:
for i in 구:
    df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/코로나/자치구별/{i}.csv')
    확진자 = []
    누적확진자 = []
    일일확진자 = []
    
    x = 0

    for j in df['date']:
        확진자.append(str(j))

    for j in date:
        y = 확진자.count(j)
        일일확진자.append(y)
        x+=y
        누적확진자.append(x)
    
    전날까지_확진자 = [0] + 누적확진자
    일일확진자_1일추가 = [0] + 일일확진자
    일일확진자_2일추가 = [0,0] + 일일확진자
    일일확진자_3일추가 = [0,0,0] + 일일확진자
    일일확진자_4일추가 = [0,0,0,0] + 일일확진자
    일일확진자_5일추가 = [0,0,0,0,0] + 일일확진자
    일일확진자_6일추가 = [0,0,0,0,0,0] + 일일확진자
    일일확진자_7일추가 = [0,0,0,0,0,0,0] + 일일확진자
    일일확진자_8일추가 = [0,0,0,0,0,0,0,0] + 일일확진자
    
    df2 = pd.DataFrame(list(zip(date,전날까지_확진자,일일확진자_1일추가,일일확진자_2일추가,일일확진자_3일추가,일일확진자_4일추가,일일확진자_5일추가,일일확진자_6일추가,일일확진자_7일추가,일일확진자_8일추가)), columns =['date', '전날누적확진자','d+1','d+2','d+3','d+4','d+5','d+6','d+7','d+8'])    
    df2['주소'] = i
    df2.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/코로나/자치구별/날짜합/{i}종합.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [14]:
for i in 구:
    지df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지하철/자치구별/날짜합/{i}종합.csv')
    코df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/코로나/자치구별/날짜합/{i}종합.csv')
    지df.rename(columns = {'사용일자' : 'date'}, inplace = True)
    df = pd.merge(지df, 코df, on ='date', how='outer')
    df.rename(columns = {'주소_x' : '주소'}, inplace = True)
    df = df.drop(['주소_y'],axis=1)
    변수df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/변수.csv')
    df = pd.merge(df, 변수df, on ='date', how='outer')
    df.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지+코+변/{i}.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [16]:
df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지+코+변/sub.csv')
df = pd.merge(df, 날씨df, on ='date', how='outer')
df = df.dropna()
df.rename(columns = {'승차총승객수' :'subway'}, inplace = True)
df.rename(columns = {'일 최심신적설(cm)' :'일적설량(cm)'}, inplace = True)
df = df.sort_values(by=['주소','date'])
df.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날.csv', encoding = 'utf-8-sig', index_label = False, index = False)

===========================

In [17]:
df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날.csv')
역갯수  = []
for i in 구:
    df2 = 역별자치구df[역별자치구df['주소'] == i]
    역갯수.append(len(df2))
df3 = pd.DataFrame(list(zip(구,역갯수)), columns =['주소', '역갯수'])   
df4 = pd.merge(df, df3, on ='주소', how='outer')
df4.to_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날역.csv', encoding = 'utf-8-sig', index_label = False, index = False)

In [18]:
인구df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/인구/자치구단위 서울생활인구 일별 집계표.csv')
인구df = 인구df[인구df['기준일ID'] >= 20190201]
인구df = 인구df[인구df['기준일ID'] <= 20210228]
인구df = 인구df[인구df['시군구명'] != '서울시']
인구df = 인구df.drop(['시군구코드','내국인생활인구수','장기체류외국인인구수','단기체류외국인인구수','일최대인구수','일최소인구수','주간인구수(09~18)','야간인구수(19~08)','일최대이동인구수','서울외유입인구수','동일자치구행정동간이동인구수','자치구간이동인구수'],axis=1)
인구df.rename(columns = {'기준일ID' : 'date'}, inplace = True)
인구df.rename(columns = {'시군구명' : '주소'}, inplace = True)
인구df.rename(columns = {'총생활인구수' : '인구수'}, inplace = True)
인구df.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/인구/구별 인구.csv', encoding = 'utf-8-sig', index_label = False, index = False)
인구df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/인구/구별 인구.csv')

In [41]:
df = pd.merge(df4, 인구df, on =['주소','date'], how='outer')
dfnull = df[df['인구수'].isnull()]
소실date = list(range(20191015, 20191028))
평균인구 = []
for i in 구:
    df2 = df[df['date'] == 20191014]
    df2 = df2[df2['주소'] == i]
    인구14 = df2.iloc[0]['인구수']
    
    df3 = df[df['date'] == 20191028]
    df3 = df3[df3['주소'] == i]
    인구28 = df3.iloc[0]['인구수']
    평균 = (인구14+인구28) / 2
    평균인구.append(평균)
df2 = pd.DataFrame(list(zip(구,평균인구)), columns =['주소', '인구수'])  
df3 = pd.merge(dfnull, df2, on ='주소', how='outer')
df3 = df3.drop(['인구수_x','subway','전날누적확진자','d+1','d+2','d+3','d+4','d+5','d+6','d+7','d+8','주말/공휴일','거리두기','마스크','4인집합','평균기온(°C)','일강수량(mm)','평균 풍속(m/s)','평균 상대습도(%)','합계 일조시간(hr)','일적설량(cm)','역갯수'],axis=1)
df3.rename(columns = {'인구수_y' : '인구수'}, inplace = True)
df최종 = pd.merge(df, df3, on =['date','주소'], how='outer')
df최종 = df최종.fillna(0)  
인구 = []
for i in range(len(df최종)):
    인구.append(df최종.iloc[i]['인구수_x'] + df최종.iloc[i]['인구수_y'])
df최종['인구'] = 인구
df최종 = df최종.drop(['인구수_x','인구수_y'],axis=1)
df최종.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날역인(채운거)(최종).csv', encoding = 'utf-8-sig', index_label = False, index = False)
df최종

,date,subway,주소,전날누적확진자,d+1,d+2,d+3,d+4,d+5,d+6,...,마스크,4인집합,평균기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),일적설량(cm),역갯수,인구
0,20190201,648428.0,강남구,0,0,0,0,0,0,0,...,0,0,-2.1,0.3,1.7,47.6,5.7,0.2,21,891474.9422
1,20190202,302248.0,강남구,0,0,0,0,0,0,0,...,0,0,1.4,0.0,1.0,60.0,1.6,0.0,21,721821.9141
2,20190203,180657.0,강남구,0,0,0,0,0,0,0,...,0,0,3.3,16.0,1.7,92.9,0.0,0.0,21,636412.8900
3,20190204,139524.0,강남구,0,0,0,0,0,0,0,...,0,0,-0.6,0.0,2.1,40.4,8.6,0.0,21,552436.3542
4,20190205,107617.0,강남구,0,0,0,0,0,0,0,...,0,0,2.8,0.0,1.0,37.1,7.8,0.0,21,520214.8117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18970,20210224,89297.0,중랑구,1151,5,4,2,5,0,3,...,1,1,2.9,0.0,1.8,33.0,8.4,0.0,8,356525.7634
18971,20210225,89238.0,중랑구,1155,4,5,4,2,5,0,...,1,1,4.2,0.0,1.4,35.1,0.0,0.0,8,356878.8077
18972,20210226,91835.0,중랑구,1159,4,4,5,4,2,5,...,1,1,8.2,0.0,2.3,35.0,9.1,0.0,8,356908.4892
18973,20210227,64893.0,중랑구,1165,6,4,4,5,4,2,...,1,1,9.5,0.0,3.4,48.6,10.3,0.0,8,368490.3312
18974,20210228,47941.0,중랑구,1168,3,6,4,4,5,4,...,1,1,7.8,0.0,2.1,49.0,2.6,0.0,8,371108.1998

In [42]:
df = pd.read_csv(f'C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날역.csv')
df = pd.merge(df, 인구df, on =['주소','date'], how='outer')
df = df.dropna()
df.to_csv('C:/Users/LEE/python/빅데이터예측모델링/데이터수집(서울만)/지코변날역인(안채운거)(최종).csv', encoding = 'utf-8-sig', index_label = False, index = False)
df

,date,subway,주소,전날누적확진자,d+1,d+2,d+3,d+4,d+5,d+6,...,마스크,4인집합,평균기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),일적설량(cm),역갯수,인구수
0,20190201,648428.0,강남구,0,0,0,0,0,0,0,...,0,0,-2.1,0.3,1.7,47.6,5.7,0.2,21,891474.9422
1,20190202,302248.0,강남구,0,0,0,0,0,0,0,...,0,0,1.4,0.0,1.0,60.0,1.6,0.0,21,721821.9141
2,20190203,180657.0,강남구,0,0,0,0,0,0,0,...,0,0,3.3,16.0,1.7,92.9,0.0,0.0,21,636412.8900
3,20190204,139524.0,강남구,0,0,0,0,0,0,0,...,0,0,-0.6,0.0,2.1,40.4,8.6,0.0,21,552436.3542
4,20190205,107617.0,강남구,0,0,0,0,0,0,0,...,0,0,2.8,0.0,1.0,37.1,7.8,0.0,21,520214.8117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18970,20210224,89297.0,중랑구,1151,5,4,2,5,0,3,...,1,1,2.9,0.0,1.8,33.0,8.4,0.0,8,356525.7634
18971,20210225,89238.0,중랑구,1155,4,5,4,2,5,0,...,1,1,4.2,0.0,1.4,35.1,0.0,0.0,8,356878.8077
18972,20210226,91835.0,중랑구,1159,4,4,5,4,2,5,...,1,1,8.2,0.0,2.3,35.0,9.1,0.0,8,356908.4892
18973,20210227,64893.0,중랑구,1165,6,4,4,5,4,2,...,1,1,9.5,0.0,3.4,48.6,10.3,0.0,8,368490.3312
18974,20210228,47941.0,중랑구,1168,3,6,4,4,5,4,...,1,1,7.8,0.0,2.1,49.0,2.6,0.0,8,371108.1998